server:
  port: 8084
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true # 开启请求方式前缀 请求方式 + 请求路径作为簇点资源名
hm:
  swagger:
    title: 支付服务接口文档
    package: com.hmall.user.controller
  db:
    database: hm-user
    host: 192.168.150.101 # 数据库主机地址
    port: 3306 # 数据库端口
    un: root # 数据库用户名
    pw: mysql_0720 # 数据库密码
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m

feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true # 开启feign对sentinel的支持